-- Checklist 2.0: user-owned deadlines (dates only, never document data).
-- A row is either a standalone deadline (linked_task_key null) or a date the
-- user attached to an existing checklist task (linked_task_key = the task's
-- order key, see utils/checklistOrder.getChecklistTaskOrderKey).
--
-- Apply via the Supabase dashboard or MCP. Do not `supabase db push`.

create table if not exists public.user_deadlines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'other'
    check (kind in ('study_permit','work_permit','pr_card','health_card','sin','tax_filing','insurance','passport','other')),
  title text not null check (char_length(btrim(title)) between 1 and 120),
  due_date date not null,
  linked_task_key text,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_deadlines_user_due_idx
  on public.user_deadlines (user_id, due_date);

-- One date per linked task per user.
create unique index if not exists user_deadlines_user_task_key_idx
  on public.user_deadlines (user_id, linked_task_key)
  where linked_task_key is not null;

alter table public.user_deadlines enable row level security;

drop policy if exists "Users can read own deadlines" on public.user_deadlines;
create policy "Users can read own deadlines"
  on public.user_deadlines for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own deadlines" on public.user_deadlines;
create policy "Users can insert own deadlines"
  on public.user_deadlines for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own deadlines" on public.user_deadlines;
create policy "Users can update own deadlines"
  on public.user_deadlines for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete own deadlines" on public.user_deadlines;
create policy "Users can delete own deadlines"
  on public.user_deadlines for delete using (auth.uid() = user_id);

create or replace function public.set_user_deadlines_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end $$;

drop trigger if exists user_deadlines_set_updated_at on public.user_deadlines;
create trigger user_deadlines_set_updated_at
  before update on public.user_deadlines
  for each row execute function public.set_user_deadlines_updated_at();
